# Generated by Django 3.1.7 on 2021-04-01 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('C', 'Compleat'), ('S', 'Success'), ('I', 'Incompleat'), ('A', 'aborted')], default='N', max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
